---
- name: Playbook to launch web server on EC2 instance for CMPE272
  hosts: webserversonec2
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install apache2 package
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        install_recommends: true
        state: latest
    - name: "Write a custom message in index.html file"
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        content: "Hello world from SJSU-{{managednode}} "
        mode: 0744
    - name: enable apache2 service
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
    - name: open firewall
      community.general.ufw:
        rule: allow
        port: 8080
        proto: tcp

